<?php

namespace AppBundle\Repository;

/**
 * ErrorLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErrorLogRepository extends \Doctrine\ORM\EntityRepository
{
}
