<?php

namespace AppBundle\Repository;

/**
 * PersonDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
