# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    result.image.manager:
        class: AppBundle\Manager\ResultImageManager
        #arguments: ['@doctrine.orm.entity_manager', 'AppBundle\Entity\Table', '@form.factory']
